#!/bin/sh

source /usr/local/bin/acq400_init_gpio_common.sh

common_begin


# si5326
mkdir -p /dev/gpio/CLK
zgpio0=$(get_zynq_gpio0)
export_gpio_value_ln $(($zgpio0+11)) /dev/gpio/CLK/LOL
export_gpio_value_ln $(($zgpio0+14)) /dev/gpio/CLK/C1B
export_gpio_value_ln $(($zgpio0+15)) /dev/gpio/CLK/C2B


# i2c gpio

CHIP122=$(get_gpiochip 1 0022)
let GPIO_1220=${CHIP122#gpiochip*}
let GPIO_1221=$GPIO_1220+23

CHIP123=$(get_gpiochip 1 0023)
let GPIO_1230=${CHIP123#gpiochip*}
let GPIO_1231=$GPIO_XX1+23


mkdir -p /dev/gpio/CHIP122
let pin=$GPIO_1220
let ix=0
#        P000102030405060710111213141516172021222324252627
for dir in O O I I I I O O O O O O O O O O O O O O O I O O
do
	export_gpio $pin

	ln -s /sys/class/gpio/gpio$pin /dev/gpio/CHIP122/$(printf P%02o $ix)
	direction=in; [ "$dir" = "O" ] && direction=out
	echo $direction > gpio$pin/direction
	let pin=$pin+1
	let ix=$ix+1
done


mkdir -p /dev/gpio/CHIP123
let pin=$GPIO_1230
let ix=0
#        P000102030405060710111213141516172021222324252627
for dir in I I I I I I O O O O O O O O O O O O I I I I I I
do
	export_gpio $pin
	ln -s /sys/class/gpio/gpio$pin /dev/gpio/CHIP123/$(printf P%02o $ix)
	direction=in; [ "$dir" = "O" ] && direction=out
	echo $direction > gpio$pin/direction
	let pin=$pin+1
	let ix=$ix+1
done


mkdir -p /dev/gpio/LED /dev/gpio/CLK /dev/gpio/MGT/SFP1 /dev/gpio/MGT/SFP2
# @todo .. compatibility link for acq400ioc
ln -s /dev/gpio/MGT /dev/gpio/MGT482
lnAH	/dev/gpio/CHIP122/P00	/dev/gpio/CLK/OE_CLK1_ELF1
lnAH	/dev/gpio/CHIP122/P01	/dev/gpio/CLK/OE_CLK1_ELF2

lnAH	/dev/gpio/CHIP122/P02	/dev/gpio/MGT/SFP1/RATE_0
lnAH	/dev/gpio/CHIP122/P03	/dev/gpio/MGT/SFP1/RATE_1
lnAH	/dev/gpio/CHIP122/P04	/dev/gpio/MGT/SFP2/RATE_0
lnAH	/dev/gpio/CHIP122/P05	/dev/gpio/MGT/SFP2/RATE_1

lnALO	/dev/gpio/CHIP122/P06	/dev/gpio/LED/FMC1_G
lnALO	/dev/gpio/CHIP122/P07	/dev/gpio/LED/FMC1_R

lnALO	/dev/gpio/CHIP122/P10	/dev/gpio/LED/SFP1_G
lnALO	/dev/gpio/CHIP122/P11	/dev/gpio/LED/SFP1_R
lnALO	/dev/gpio/CHIP122/P12	/dev/gpio/LED/SFP2_G
lnALO	/dev/gpio/CHIP122/P13	/dev/gpio/LED/SFP2_R

lnALO	/dev/gpio/CHIP122/P14	/dev/gpio/LED/CLK_G
lnALO	/dev/gpio/CHIP122/P15	/dev/gpio/LED/CLK_R

lnAH	/dev/gpio/CHIP122/P16	/dev/gpio/CLK/OE_CLK1_ZYNQ
lnALO	/dev/gpio/CHIP122/P17	/dev/gpio/CLK/OE_CLK1_HDMI

lnAH	/dev/gpio/CHIP122/P20	/dev/gpio/FAN_EN

echo 1 > /dev/gpio/FAN_EN

lnAH 	/dev/gpio/CHIP122/P21 	/dev/gpio/FP_SYNC_DIR_OUT
lnAH 	/dev/gpio/CHIP122/P22 	/dev/gpio/FP_IO_DIR_OUT
lnAH 	/dev/gpio/CHIP122/P23 	/dev/gpio/SYNC_IN_GPIO_OUT
lnAH 	/dev/gpio/CHIP122/P24 	/dev/gpio/SYNC_OUT_GPIO_OUT
setHI   /dev/gpio/CHIP122/P24/value                           # Set high for Sync Bus Output GPIO to be an  Output (default)
lnAL 	/dev/gpio/CHIP122/P25 	/dev/gpio/SYNC_CABLE_DET

lnAH 	/dev/gpio/CHIP122/P26 	/dev/gpio/MGT/SFP1/TX_DISABLE
lnAH 	/dev/gpio/CHIP122/P27 	/dev/gpio/MGT/SFP2/TX_DISABLE



lnAL	/dev/gpio/CHIP123/P00	/dev/gpio/fmc1_present
lnAL	/dev/gpio/CHIP123/P01	/dev/gpio/fmc2_present

lnAL	/dev/gpio/CHIP123/P02	/dev/gpio/MGT/SFP1/PRESENT
lnAL	/dev/gpio/CHIP123/P03	/dev/gpio/MGT/SFP2/PRESENT

lnAH	/dev/gpio/CHIP123/P04	/dev/gpio/MGT/SFP1/TX_FAULT
lnAH	/dev/gpio/CHIP123/P05	/dev/gpio/MGT/SFP2/TX_FAULT

lnALO	/dev/gpio/CHIP123/P06	/dev/gpio/LED/FMC2_G
lnALO	/dev/gpio/CHIP123/P07	/dev/gpio/LED/FMC2_R

lnALO	/dev/gpio/CHIP123/P10	/dev/gpio/CLK/ZCLK_OE
lnAH	/dev/gpio/CHIP123/P11	/dev/gpio/CLK/DIST_CLK_HDMI  # Not CLK1
lnALO	/dev/gpio/CHIP123/P12	/dev/gpio/CLK/OSC_X_OE
lnALO	/dev/gpio/CHIP123/P13	/dev/gpio/CLK/OSC_X_CLK_OE
lnALO	/dev/gpio/CHIP123/P14	/dev/gpio/CLK/FP_CLK_OE
lnALO	/dev/gpio/CHIP123/P15	/dev/gpio/CLK/FP_OE
lnALO	/dev/gpio/CHIP123/P16	/dev/gpio/CLK/Si570_OE




lnALO	/dev/gpio/CHIP123/P20	/dev/gpio/LED/TRG_G
lnALO	/dev/gpio/CHIP123/P21	/dev/gpio/LED/TRG_R

lnAH 	/dev/gpio/CHIP123/P22	/dev/gpio/MGT/SFP1/LOS
lnAH 	/dev/gpio/CHIP123/P23	/dev/gpio/MGT/SFP2/LOS

ln		/dev/gpio/CHIP123/P24	/dev/gpio/BV1
ln		/dev/gpio/CHIP123/P25	/dev/gpio/BV2
ln		/dev/gpio/CHIP123/P26	/dev/gpio/BV3
ln		/dev/gpio/CHIP123/P27	/dev/gpio/BV4

echo HDMI sync setting /dev/gpio/CLK/SYNC_SET_IN as INPUT 0
set.sys /dev/gpio/CLK/SYNC_SET_IN 0
echo HDMI sync setting /dev/gpio/CLK/SYNC_SET_OUT as OUTPUT 1
set.sys /dev/gpio/CLK/SYNC_SET_OUT 1

/sbin/insmod /usr/local/lib/modules/si5326.ko
	

mkdir -p /dev/acq2006/
ln -s /sys/bus/i2c/devices/1-002c/rdac0 /dev/acq2006/vap
ln -s /sys/bus/i2c/devices/1-002c/rdac1 /dev/acq2006/van

echo +++ setting VAP and VAN to MIN BEFORE touching gpio
echo 2 > /dev/acq2006/vap
echo 2 > /dev/acq2006/van

echo +++ now set 15VA_EN direction out
[ -e dev/gpio/15VA_EN ] && (echo WARNING: deleting pre-existing 15VA_EN; rm dev/gpio/15VA_EN)
lnALO   /dev/gpio/CHIP123/P17   /dev/gpio/15VA_EN

common_end

echo "++ acq1001_init_gpio done"
